/**
 * AIBadge - Small, unobtrusive badge indicating AI-generated content.
 * Used to clearly distinguish AI output from factual data,
 * reminding teachers that they make the final judgment.
 */

interface AIBadgeProps {
  className?: string;
}

export function AIBadge({ className = "" }: AIBadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-1 text-[10px] text-stone/70 uppercase tracking-wider ${className}`}
      title="This content was generated by AI"
    >
      {/* Sparkle icon */}
      <svg
        className="w-3 h-3"
        viewBox="0 0 16 16"
        fill="currentColor"
        aria-hidden="true"
      >
        <path d="M8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 11a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2a.5.5 0 0 1 .5-.5zm5-3a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2A.5.5 0 0 1 3 8zm8.354-3.646a.5.5 0 0 1 0 .708l-1.414 1.414a.5.5 0 1 1-.708-.708l1.414-1.414a.5.5 0 0 1 .708 0zm-7.778 7.778a.5.5 0 0 1 0 .708l-.707.707a.5.5 0 0 1-.708-.708l.707-.707a.5.5 0 0 1 .708 0zm7.778 0a.5.5 0 0 1 .708 0l.707.707a.5.5 0 0 1-.708.708l-.707-.707a.5.5 0 0 1 0-.708zM4.646 4.354a.5.5 0 0 1-.708 0l-.707-.707a.5.5 0 0 1 .708-.708l.707.707a.5.5 0 0 1 0 .708z" />
      </svg>
      ai
    </span>
  );
}
